from __future__ import annotations

import argparse
import json
import re
import shutil
import urllib.parse
from pathlib import Path

from ws_lib import career, catalog, literature, paths, project, relations, yamlish


WORKSPACE = paths.WORKSPACE
KNOWLEDGEBASE = paths.KNOWLEDGEBASE
GENERATED = KNOWLEDGEBASE / "generated"

GENERATED_NOTE = "> [!note] Generated by `ws wiki build` — do not edit. Regenerate with `ws wiki build`."


def frontmatter(tags: list[str], props: dict | None = None, aliases: list[str] | None = None) -> str:
    lines = ["---", "tags:"]
    lines.extend(f"  - {tag}" for tag in tags)
    if aliases:
        lines.append("aliases:")
        lines.extend(f"  - {json.dumps(alias, ensure_ascii=False)}" for alias in aliases)
    for key, value in (props or {}).items():
        lines.append(f"{key}: {value}")
    lines.append("generated: true")
    lines.append("---")
    return "\n".join(lines)


def file_link(target: Path) -> str:
    """Link a real workspace file as a file:// URL. The vault is wiki/ alone;
    everything outside it opens in the system viewer instead of being
    indexed by Obsidian as a vault member."""
    return "file://" + urllib.parse.quote(str(Path(target).resolve()), safe="/")


def emit(note: Path, lines: list[str]) -> None:
    note.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")


def compact(value: str) -> str:
    return re.sub(r"\s+", " ", value).strip()


def safe_label(value: str) -> str:
    return compact(value).replace("|", "-").replace("]", ")")


def wiki_link(node: str, label: str = "") -> str:
    return f"[[{node}|{safe_label(label)}]]" if label else f"[[{node}]]"


def pnode(name: str) -> str:
    """Flatten a project relpath into a single vault-note id (no path separators)."""
    return name.replace("/", "--")


def plink(name: str) -> str:
    """Wikilink to a project note; nested projects show their readable relpath as label."""
    return f"[[{name}]]" if "/" not in name else wiki_link(pnode(name), name)


def project_ref_link(ref: str, known) -> str:
    """Render a project cross-reference, resolving a leaf name to its full path."""
    canon = project.normalize_ref(ref, known)
    return plink(canon) if canon else f"{ref}  (unknown project)"


def has_heading(path: Path, heading: str) -> bool:
    if not path.exists():
        return False
    return bool(re.search(rf"^##\s+{re.escape(heading)}\s*$", project.read(path), flags=re.MULTILINE | re.IGNORECASE))


def embed_section(path: Path, heading: str) -> str:
    """Inline a markdown section at build time. Transclusion (![[note#h]])
    would require the source file to live inside the vault; the vault holds
    generated notes only."""
    text = project.read(path)
    match = re.search(
        rf"^##\s+{re.escape(heading)}\s*$(.*?)(?=^##\s|\Z)",
        text,
        flags=re.MULTILINE | re.DOTALL | re.IGNORECASE,
    )
    return match.group(1).strip() if match else ""


def parse_info_yaml(path: Path) -> dict:
    data: dict = {"keywords": [], "fields": [], "subfields": [], "summary": ""}
    if not path.exists():
        return data
    parsed = yamlish.load_mapping(project.read(path))
    for key in ("keywords", "fields", "subfields"):
        values = parsed.get(key)
        if isinstance(values, list):
            data[key] = [str(value) for value in values]
    value = parsed.get("summary")
    if value is not None and not isinstance(value, (list, dict)):
        data["summary"] = str(value)
    return data


def discover_literature() -> dict[str, dict]:
    items: dict[str, dict] = {}
    for bib_path in literature.list_item_bibtex_files():
        bibtex = literature.read(bib_path)
        key = bib_path.parent.name
        info = parse_info_yaml(bib_path.parent / "info.yaml")
        items[key] = {
            "dir": bib_path.parent,
            "key": key,
            "title": compact(literature.bibtex_field(bibtex, "title")) or key,
            "author": compact(literature.bibtex_field(bibtex, "author")),
            "authors": literature.bibtex_authors(bibtex),
            "year": compact(literature.bibtex_field(bibtex, "year")),
            "doi": literature.bibtex_doi(bibtex),
            "keywords": info["keywords"],
            "fields": info["fields"],
            "subfields": info["subfields"],
            "summary": info["summary"],
        }
    return items


def literature_node_id(key: str) -> str:
    return f"literature-{key}"


OBJECT_DIRS = {
    "person": "people",
    "organisation": "organisations",
    "event": "events",
    "task": "tasks",
    "document": "documents",
    "resource": "resources",
}


def object_node_id(ref: catalog.ObjectRef) -> str:
    if ref.type == "project":
        return pnode(ref.id.split(":", 1)[1])
    if ref.type == "literature":
        return literature_node_id(ref.id.split(":", 1)[1])
    if ref.type == "profile":
        # Profile objects are privacy-filtered into one aggregate page rather
        # than emitted as raw per-object wiki notes.
        return "profile/profile"
    # Obsidian shows filenames in the explorer and graph, so notes are named
    # by kind and key -- as immutable as the ULID, but human-readable.
    return f"{ref.type}-{ref.ref.partition(':')[2]}"


def object_wikilink(ref: catalog.ObjectRef) -> str:
    return wiki_link(object_node_id(ref), ref.title)


def relationship_section(object_id: str, object_map: dict[str, catalog.ObjectRef], rows: list[dict]) -> list[str]:
    related = [
        row for row in rows
        if row.get("subject") == object_id or row.get("object") == object_id
    ]
    if not related:
        return []
    lines = ["## Workspace relationships", ""]
    for row in related:
        outgoing = row.get("subject") == object_id
        other_id = str(row.get("object") if outgoing else row.get("subject"))
        other = object_map.get(other_id)
        label = object_wikilink(other) if other else f"`{other_id}` (missing)"
        arrow = "→" if outgoing else "←"
        lines.append(f"- `{row.get('relation', 'related')}` {arrow} {label}")
    lines.append("")
    return lines


def command_wiki(_args: argparse.Namespace) -> None:
    if GENERATED.exists():
        generated = GENERATED.resolve()
        if (
            generated.name != "generated"
            or generated != (KNOWLEDGEBASE / "generated").resolve()
            or generated in (Path("/"), Path.home().resolve())
        ):
            project.fail("refusing to clear unexpected generated path")
        shutil.rmtree(generated)
    for sub in [
        "projects", "literature", "profile", "fields",
        "people", "organisations", "events", "tasks", "documents", "resources",
    ]:
        (GENERATED / sub).mkdir(parents=True, exist_ok=True)

    projects = project.existing_project_names()
    known = set(projects)
    project_meta = {name: project.parse_project_yaml(project.PROJECTS / name / "project.yaml") for name in projects}
    literature_items = discover_literature()
    career_profile = career.load_profile()
    identity = career_profile.get("identity", {}) or {}
    own_publication_keys = career.publication_literature_keys(career_profile)
    catalog_objects = catalog.all_objects()
    object_map = {obj.id: obj for obj in catalog_objects}
    relationship_rows = relations.load_all()

    effective_related: dict[str, set[str]] = {name: set() for name in projects}
    used_by: dict[str, set[str]] = {name: set() for name in projects}
    for name, meta in project_meta.items():
        for related_name in meta["related"]:
            canon = project.normalize_ref(related_name, known)
            if canon:
                effective_related[name].add(canon)
                effective_related[canon].add(name)
        for dependency in meta["depends_on"]:
            canon = project.normalize_ref(dependency, known)
            if canon:
                used_by[canon].add(name)

    field_to_projects: dict[str, list[str]] = {}
    for field in project.load_taxonomy()["fields"]:
        field_to_projects.setdefault(field, [])
    for name in projects:
        for field in project_meta[name]["fields"]:
            field_to_projects.setdefault(field, []).append(name)

    # Project nodes
    for name in projects:
        meta = project_meta[name]
        note = GENERATED / "projects" / f"{pnode(name)}.md"
        tags = (
            ["kind/project"]
            + [f"field/{f}" for f in meta["fields"]]
            + [f"subfield/{f}" for f in meta["subfields"]]
        )
        if meta["status"]:
            tags.append(f"status/{meta['status']}")
        props = {}
        if meta["type"]:
            props["type"] = meta["type"]
        if meta["status"]:
            props["status"] = meta["status"]
        lines = [frontmatter(tags, props), "", GENERATED_NOTE, "", f"# {name}", ""]
        if meta["title"]:
            lines += [f"**{meta['title']}**", ""]
        descriptor = " · ".join(filter(None, [
            f"Type: {meta['type']}" if meta["type"] else "",
            f"Status: {meta['status']}" if meta["status"] else "",
        ]))
        if descriptor:
            lines += [descriptor, ""]
        if meta["fields"]:
            lines += ["Fields: " + ", ".join(f"[[field-{f}]]" for f in meta["fields"]), ""]
        if meta["subfields"]:
            lines += ["Subfields: " + ", ".join(f"`{value}`" for value in meta["subfields"]), ""]
        if meta["keywords"]:
            lines += ["Keywords: " + ", ".join(f"`{keyword}`" for keyword in meta["keywords"]), ""]
        if meta["depends_on"]:
            lines.append("## Depends on")
            lines += [f"- {project_ref_link(d, known)}" for d in meta["depends_on"]]
            lines.append("")
        if effective_related[name] or any(r not in known for r in meta["related"]):
            lines.append("## Related")
            lines += [f"- {plink(r)}" for r in sorted(effective_related[name])]
            lines += [f"- {r}  (external)" for r in meta["related"] if project.normalize_ref(r, known) is None]
            lines.append("")
        if used_by[name]:
            lines.append("## Used by")
            lines += [f"- {plink(source)}" for source in sorted(used_by[name])]
            lines.append("")
        if meta["related_literature"]:
            lines.append("## Related literature")
            for key in meta["related_literature"]:
                item = literature_items.get(key)
                lines.append(f"- {wiki_link(literature_node_id(key), item['title'])}" if item else f"- {key}  (unknown item)")
            lines.append("")
        readme = project.PROJECTS / name / "README.md"
        for heading, display in [("Purpose", "Project overview"), ("Current State", "Current state"), ("Next Steps", "Next steps")]:
            if has_heading(readme, heading):
                lines += [f"## {display}", "", embed_section(readme, heading), ""]
        capabilities = [
            label for key, label in [
                ("has_code", "code"), ("has_paper", "paper"),
                ("has_data", "data"), ("server_compute", "server compute"),
            ] if str(meta.get(key, "")).lower() == "true"
        ]
        if capabilities or meta["hosts"]:
            lines.append("## Workspace metadata")
            if capabilities:
                lines.append("- Capabilities: " + ", ".join(capabilities))
            if meta["hosts"]:
                lines.append("- Hosts: " + ", ".join(meta["hosts"]))
            lines.append("")
        lines += relationship_section(f"project:{name}", object_map, relationship_rows)
        lines.append("## Files")
        for fname in ["README.md", "AGENTS.md", "project.yaml"]:
            lines.append(f"- [{fname}]({file_link(project.PROJECTS / name / fname)})")
        emit(note, lines)

    # Literature nodes
    for key, item in literature_items.items():
        note = GENERATED / "literature" / f"{literature_node_id(key)}.md"
        tags = ["kind/literature"]
        for field in item["fields"]:
            tags.append(f"field/{field}")
        for subfield in item["subfields"]:
            tags.append(f"subfield/{subfield}")
        lines = [frontmatter(tags, {"year": item["year"]} if item["year"] else None), "", GENERATED_NOTE, "", f"# {item['title']}", ""]
        descriptor = " · ".join(filter(None, [item["author"], item["year"]]))
        if descriptor:
            lines += [descriptor, ""]
        if item["doi"]:
            lines += [f"DOI: [{item['doi']}](https://doi.org/{item['doi']})", ""]
        if item["keywords"]:
            lines += ["Keywords: " + ", ".join(f"`{keyword}`" for keyword in item["keywords"]), ""]
        if item["fields"]:
            lines += ["Fields: " + ", ".join(f"[[field-{field}]]" for field in item["fields"]), ""]
        if item["subfields"]:
            lines += ["Subfields: " + ", ".join(f"`{value}`" for value in item["subfields"]), ""]
        if item["summary"]:
            lines += ["## Summary", "", item["summary"], ""]
        item_projects = [name for name in projects if key in project_meta[name]["related_literature"]]
        if item_projects:
            lines += ["## Projects"] + [f"- {plink(name)}" for name in item_projects] + [""]
        lines += relationship_section(f"literature:{key}", object_map, relationship_rows)
        lines += ["## Files", f"- [citation.bib]({file_link(item['dir'] / 'citation.bib')})"]
        for fname in ["info.yaml", "summary.md", "notes.md"]:
            if (item["dir"] / fname).exists():
                lines.append(f"- [{fname}]({file_link(item['dir'] / fname)})")
        emit(note, lines)

    # Privacy-filtered career views. Contact details, date of birth, address,
    # proof paths, and application contents deliberately stay out of the wiki.
    profile_by_type = career_profile.get("by_type", {}) or {}

    profile_note = GENERATED / "profile" / "profile.md"
    profile_lines = [
        frontmatter(["kind/profile"]),
        "",
        GENERATED_NOTE,
        "",
        "# Professional profile",
        "",
    ]
    display_name = " ".join(filter(None, [str(identity.get("name", "")), str(identity.get("post_nominals", ""))]))
    if display_name:
        profile_lines += [f"**{display_name}**", ""]
    if identity.get("headline"):
        profile_lines += [str(identity["headline"]), ""]
    if identity.get("description"):
        profile_lines += [str(identity["description"]), ""]
    if identity.get("orcid"):
        orcid = str(identity["orcid"])
        profile_lines += [f"ORCID: [{orcid}](https://orcid.org/{orcid})", ""]
    profile_lines += [
        "## CV sections",
        "",
        "| Type | Active objects | Browse view |",
        "|---|---:|---|",
    ]
    for type_id in career.profile_taxonomy.type_ids():
        if type_id == "identity":
            continue
        refs = profile_by_type.get(type_id, [])
        view = career.CAREER / "by-type" / type_id
        profile_lines.append(
            f"| {type_id.replace('-', ' ').title()} | {len(refs)} | "
            f"[by-type/{type_id}]({file_link(view)}) |"
        )
    profile_lines += ["", "Return to [[Profile]]."]
    emit(profile_note, profile_lines)

    skills_note = GENERATED / "profile" / "skills.md"
    skills_lines = [
        frontmatter(["kind/profile-skills"]),
        "",
        GENERATED_NOTE,
        "",
        "# Profile skills",
        "",
    ]
    skill_refs = profile_by_type.get("skill", [])
    if skill_refs:
        for ref in skill_refs:
            data = ref.data or {}
            skills_lines += [f"## {ref.title}", ""]
            if data.get("description"):
                skills_lines += [str(data["description"]), ""]
            skills_lines += [f"- {item}" for item in data.get("bullets", [])]
            if ref.path:
                skills_lines += [f"[Canonical record]({file_link(ref.path)})", ""]
    else:
        skills_lines.append("_No skill objects recorded._")
    skills_lines += [
        "Return to [[Profile]].",
    ]
    emit(skills_note, skills_lines)

    profile_hub = GENERATED / "Profile.md"
    profile_hub_lines = [
        frontmatter(["kind/profile"]),
        "",
        GENERATED_NOTE,
        "",
        "# Profile",
        "",
        "- [[profile/profile|Professional profile]]",
        "- [[profile/skills|Skills and research interests]]",
    ]
    linked_publications = [key for key in own_publication_keys if key in literature_items]
    profile_hub_lines += ["", "## Publications", ""]
    if linked_publications:
        for key in linked_publications:
            profile_hub_lines.append(f"- {wiki_link(literature_node_id(key), literature_items[key]['title'])}")
    else:
        profile_hub_lines.append("_No publication objects represent literature items._")
    profile_hub_lines += [
        "",
        "## Related workspace views",
        "",
        "- [[Literature]]",
        "",
        "## Files",
        f"- [Profile README]({file_link(career.CAREER / 'README.md')})",
        f"- [Profile objects]({file_link(career.ITEMS)})",
        f"- [Profile taxonomy]({file_link(career.TAXONOMY)})",
    ]
    emit(profile_hub, profile_hub_lines)

    # Field nodes
    for field in sorted(field_to_projects):
        note = GENERATED / "fields" / f"field-{field}.md"
        lines = [frontmatter(["kind/field"]), "", GENERATED_NOTE, "", f"# Field: {field}", ""]
        configured_subfields = project.subfield_map().get(field, [])
        if configured_subfields:
            lines += ["Subfields: " + ", ".join(f"`{value}`" for value in configured_subfields), ""]
        members = sorted(field_to_projects[field])
        if members:
            lines.append("Projects:")
            lines += [f"- {plink(p)}" for p in members]
        else:
            lines.append("_No projects yet._")
        emit(note, lines)

    # Registered object nodes. Communications remain part of logistics and are
    # intentionally omitted until a local communication object lifecycle is
    # introduced; provider-owned email drafts stay with the mail client.
    generic_objects = [
        obj for obj in catalog_objects
        if obj.type in OBJECT_DIRS
        and obj.type not in {"project", "literature"}
        # Merged tombstones redirect to their canonical record; the wiki
        # renders only living objects.
        and str((obj.data or {}).get("status", "")) != "merged"
    ]
    for obj in generic_objects:
        directory = OBJECT_DIRS[obj.type]
        note = GENERATED / directory / f"{object_node_id(obj)}.md"
        data = obj.data or {}
        props = {"ws_id": obj.id, "kind": obj.type}
        status = str(data.get("status", ""))
        if status:
            props["status"] = status
        lines = [
            frontmatter([f"kind/{obj.type}"], props, aliases=[obj.title]),
            "",
            GENERATED_NOTE,
            "",
            f"# {obj.title}",
            "",
        ]
        visible_fields = [
            ("kind", "Kind"), ("status", "Status"), ("start", "Start"), ("end", "End"),
            ("timezone", "Timezone"), ("location", "Location"), ("due", "Due"),
            ("priority", "Priority"),
        ]
        for key, label in visible_fields:
            if data.get(key) not in (None, "", []):
                lines.append(f"- **{label}:** {data[key]}")
        if any(data.get(key) not in (None, "", []) for key, _ in visible_fields):
            lines.append("")
        if obj.type == "document" and catalog.document_type(data):
            lines += [f"- **Document type:** {catalog.document_type(data)}", ""]
        lines += relationship_section(obj.id, object_map, relationship_rows)
        if obj.type == "document" and data.get("path"):
            document_path = (
                paths.DOCUMENTS / str(data["path"])
                if data.get("path_root") == "documents"
                else Path(str(data["path"]))
            )
            lines += ["## File", "", f"- [{document_path.name}]({file_link(document_path)})", ""]
        if obj.type == "resource" and obj.path:
            resource_files = [
                path for path in sorted(obj.path.parent.rglob("*"))
                if path.is_file() and path != obj.path and not path.name.startswith(".")
            ]
            lines += ["## Files", ""]
            lines += [
                f"- [{path.relative_to(obj.path.parent)}]({file_link(path)})"
                for path in resource_files
            ] or ["_No files yet._"]
            lines.append("")
        if obj.path:
            lines += ["## Canonical record", "", f"- [{obj.path.name}]({file_link(obj.path)})"]
        emit(note, lines)

    # Index maps-of-content
    proj_lines = [frontmatter(["kind/index"]), "", GENERATED_NOTE, "", "# Projects", "", "| Project | Status | Type | Fields | Subfields |", "|---|---|---|---|---|"]
    if projects:
        for name in projects:
            meta = project_meta[name]
            proj_lines.append(f"| {plink(name)} | {meta['status']} | {meta['type']} | {', '.join(meta['fields'])} | {', '.join(meta['subfields'])} |")
    else:
        proj_lines.append("_No projects yet._")
    emit(GENERATED / "Projects.md", proj_lines)

    literature_lines = [frontmatter(["kind/index"]), "", GENERATED_NOTE, "", "# Literature", "", "| Item | Authors | Year | Fields | Subfields |", "|---|---|---|---|---|"]
    if literature_items:
        for key, item in literature_items.items():
            literature_lines.append(f"| {wiki_link(literature_node_id(key), item['title'])} | {', '.join(item['authors'])} | {item['year']} | {', '.join(item['fields'])} | {', '.join(item['subfields'])} |")
    else:
        literature_lines.append("_No literature items yet._")
    emit(GENERATED / "Literature.md", literature_lines)

    connection_lines = [frontmatter(["kind/index"]), "", GENERATED_NOTE, "", "# Connections", ""]
    project_pairs = sorted({tuple(sorted((name, other))) for name in projects for other in effective_related[name] if name != other})
    connection_lines.append("## Related projects")
    connection_lines += [f"- {plink(left)} ↔ {plink(right)}" for left, right in project_pairs] or ["_None._"]
    connection_lines += ["", "## Project literature"]
    project_literature_lines = []
    for name in projects:
        for key in project_meta[name]["related_literature"]:
            item = literature_items.get(key)
            project_literature_lines.append(f"- {plink(name)} ↔ {wiki_link(literature_node_id(key), item['title'] if item else key)}")
    connection_lines += project_literature_lines or ["_None._"]
    connection_lines += [
        "",
        "## Profile",
        "- [[Profile]] ↔ [[profile/profile]]",
        "- [[Profile]] ↔ [[profile/skills]]",
    ]
    connection_lines += ["", "## Shared object graph"]
    shared_lines = []
    for row in relationship_rows:
        subject = object_map.get(str(row.get("subject", "")))
        object_ref = object_map.get(str(row.get("object", "")))
        left = object_wikilink(subject) if subject else f"`{row.get('subject')}` (missing)"
        right = object_wikilink(object_ref) if object_ref else f"`{row.get('object')}` (missing)"
        shared_lines.append(f"- {left} — `{row.get('relation', 'related')}` → {right}")
    connection_lines += shared_lines or ["_None._"]
    emit(GENERATED / "Connections.md", connection_lines)

    field_lines = [frontmatter(["kind/index"]), "", GENERATED_NOTE, "", "# Fields", ""]
    if field_to_projects:
        for field in sorted(field_to_projects):
            field_lines.append(f"- [[field-{field}]] ({len(field_to_projects[field])})")
    else:
        field_lines.append("_No fields yet._")
    emit(GENERATED / "Fields.md", field_lines)

    for type_name, directory in OBJECT_DIRS.items():
        members = sorted((obj for obj in generic_objects if obj.type == type_name), key=lambda obj: obj.title.casefold())
        title = directory.replace("-", " ").title()
        lines = [frontmatter(["kind/index"]), "", GENERATED_NOTE, "", f"# {title}", ""]
        lines += [f"- {object_wikilink(obj)}" for obj in members] or [f"_No {directory} yet._"]
        emit(GENERATED / f"{title}.md", lines)

    home = [
        frontmatter(["kind/home"]), "", GENERATED_NOTE, "", "# Workspace", "",
        "- [[Connections]]", "- [[Projects]]", "- [[Tasks]]", "- [[Notes]]",
        "- [[Documents]]", "- [[People]]", "- [[Organisations]]", "- [[Events]]",
        "- [[Agents]]", "- [[Profile]]", "- [[Literature]]", "- [[Fields]]",
    ]
    emit(GENERATED / "Workspace.md", home)

    print(f"wrote wiki: {project.rel_home(GENERATED)}")
    print(
        f"projects: {len(projects)}  literature: {len(literature_items)}  "
        f"registered: {len(generic_objects)}  "
        f"relations: {len(relationship_rows)}  profile: 1  fields: {len(field_to_projects)}"
    )


def command_wiki_help(args: argparse.Namespace) -> None:
    args.root_parser.print_help()


def add_parser(sub: argparse._SubParsersAction) -> None:
    parser = sub.add_parser("wiki", help="generate and inspect the derived Obsidian/wiki layer")
    actions = parser.add_subparsers(dest="wiki_command")
    build = actions.add_parser(
        "build",
        help="rebuild the generated wiki",
        description="Rebuild the generated Obsidian vault from every domain "
        "and the relations graph.",
    )
    build.set_defaults(func=command_wiki)
    # Building has one spelling, `ws wiki build`; bare `ws wiki` is a heading.
    parser.set_defaults(func=command_wiki_help, root_parser=parser)
