"""Demo: build one deck per installed theme, exercising the slide types.

    python3 demo.py            ->  out/demo/<theme>_demo.pptx

Placeholder figures are generated into out/demo/assets/; out/ is ignored by
git, so running the demo never touches tracked files.
"""
from pathlib import Path

import demo_assets
from slide_factory import Deck, card_item, list_themes

HERE = Path(__file__).parent
OUT = HERE / "out" / "demo"
ASSETS = demo_assets.build(OUT / "assets")

REFS = [
    "A. Author et al., Journal of Examples 5, 040328 (2023).",
    "B. Writer et al., Journal of Examples 6, 010901 (2025).",
    "C. Scholar et al., arXiv:0000.00000 (2025).",
    "D. Reader et al., Example Letters 111, 195302 (2025).",
]

BULLETS = [
    "Solve the Poisson equation for realistic device electrostatics",
    ("Position-dependent permittivity ε(r) and charge density ρ(r)", 1),
    "Pre-computed Green's functions give the total potential cheaply",
    ("Linear superposition:  V = V₁·GF₁ + V₂·GF₂", 1),
    "FFT-based, matrix-free construction of the grid Hamiltonian",
    "Spectral method: Lanczos diagonalisation in a co-moving basis",
    ("Dynamical phases applied per step, projected onto the next eigenbasis", 1),
]


def build(theme: str, out: Path) -> Path:
    deck = Deck(theme=theme)

    deck.title_slide(
        "Modelling Electron Shuttling in Si/SiO2 devices",
        authors=["A. Author", "B. Writer", "C. Scholar"],
        notes="Generated by slide_factory — replace content and go.",
    )

    deck.two_picture_slide(
        "Why we want to shuttle?",
        pictures=[(ASSETS["pipeline"], "Looped pipeline architecture"),
                  (ASSETS["snakes"], "Snakes-on-a-plane architecture")],
        takeaway="Low adiabatic error rates",
        references=REFS,
    )

    deck.picture_bullets_slide(
        "Modelling framework for fast charge shuttling simulations",
        picture=ASSETS["wells"],
        bullets=BULLETS,
        bullets_heading="Electrostatics → Schrödinger evolution",
        caption="Instantaneous eigenstates of the travelling double-well potential",
        references=REFS[:2],
    )

    deck.picture_slide(
        "Electrostatics of the shuttling device",
        picture=ASSETS["device"],
        caption="Gate stack cross-section: conveyor-mode shuttling channel",
        takeaway="Green's functions make full-device electrostatics cheap",
    )

    deck.picture_stack_slide(
        "From device to architecture (click to build up)",
        pictures=[(ASSETS["device"], "1 — gate-defined shuttling channel"),
                  (ASSETS["wells"], "2 — travelling double-well potential"),
                  (ASSETS["pipeline"], "3 — looped pipeline architecture")],
        takeaway="Each click reveals the next stage",
    )

    deck.bullets_slide(
        "Why simulate?",
        [("Speed", "development cycle from months to hours"),
         ("Insight", "watch the wavefunctions in the device"),
         "A plain bullet without a lead-in word"],
    )

    deck.columns_slide(
        "Work packages",
        [
            ("Theory", "What exists: SiGe", [
                card_item("Effective models", tag="PUBLISHED",
                          tag_color=deck.theme.primary),
                card_item("Spin-orbit coupling", sub="g-factors from first principles"),
            ]),
            ("Methods", None, [
                "Time dynamics",
                card_item("Relaxation", tag="MAYBE", muted=True),
            ]),
        ],
        weights=[3, 2], card_h=3.6,
        legend="Cards take plain strings or card_item(...) entries",
    )

    deck.timeline_slide(
        "Plan",
        ["Sep", "Oct", "Nov", "Dec", "Jan", "Feb"],
        milestones=[(2.0, "End of October", "First result"),
                    (4.0, "End of December", "Paper submitted")],
        spans=[(2.0, 4.0, "Writing", False), (4.0, 6.0, "Release", True)],
        subtitle="Milestones above, work bars below",
        aside=(0.2, 1.8, "Optional extras"),
    )

    return deck.save(out)


if __name__ == "__main__":
    for theme in list_themes():
        print("built:", build(theme, OUT / f"{theme}_demo.pptx"))
